inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/**/*
    - scratch/*
    - config/**/*
    - vendor/**/*

Metrics/LineLength:
  Max: 120
