version: '2'
services:
  postgres:
    image: postgres
  redis:
    image: redis
  findahome:
    environment:
      - SECRET_KEY_BASE=secret
    build: .
    image: howdoicomputer/findahome
    ports:
      - "3000:3000"
    volumes:
      - .:/findahome
    links:
      - postgres
      - redis
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
